### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.dom.ASTConverter*` test suites

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#58]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
ASTConverterTestAST3_2.test0697 is failing because the parser doesn't set `forceMethodRecovery` by default in ASTParser, while the finer grain legacy parser-based implementation explicitly sets it.
The only viable fix seems to be in CompilationUnitResolver, independent of DOM-based (a new test case could be written reproducing this issue).

**Comment by mickaelistria** [comment]
The discussion https://github.com/eclipse-jdt/eclipse.jdt.core/discussions/2130 is about this test0697. I checked locally, and if I force in CompilationUnitResolver `performMethodsFullRecovery`, the test gets fixed.

**Comment by datho7561** [comment]
I'm interested in fixing ASTConverter9Test.testBug515875_001, which fails due to a StackOverflow

**Comment by mickaelistria** [comment]
All fixed or ignored.
