### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.JavaSearchTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#61]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
I found 2 causes of issues here:
* ResolvedVariableBinding (when type is not resolved) failing at returning a proper IJavaElement in codeSelect (either this can be fixed in JDT Core, or we need some workaround that doesn't rely on the binding resolver since the goal is to use Javac one as well). I experimentally created https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/129 .
* Field Declaration of form `@Annot int x, y;` are not properly populating the model: the annotation is only added to the last variable, not all of them. Submitted https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/130 to hopefully fix it.

**Comment by mickaelistria** [comment]
All fixed (or ignored if not relevant to Javac work)
