### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.JavaSearchGenericFieldTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#63]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
The remaining tests are failing because the Search (which still relies on ECJ parser) does expect that the LocalVariable JavaElement for a method parameter starts just after the previous comma, including potential comments that are placed between.
The current implementation in DOMToModelPopulator uses the token location.

The culprit line is in LocalVariableLocator, line 42 `if (node.declarationSourceStart == getLocalVariable().declarationSourceStart)` which should return true.

A workaround can be implemented in DOMToModelPopulator to make this test pass.
However, we should instead consider making the Search use a DOM visitor as well (I had forgotten about that parser).

**Comment by mickaelistria** [comment]
Reported upstream issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2310 than ignored test as it doesn't seem so trivial to fix, nor relevant for further Javac stuff
