### ISSUE TITLE
[DOM-first] Fix `org.eclipse.jdt.core.tests.model.JavaSearchBugsTests` test suite

### ISSUE THREAD

**Issue by datho7561** [eclipse-jdtls/eclipse-jdt-core-incubator#68]
See https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/12, treat this as a subissue for that epic

**Comment by mickaelistria** [comment]
One issue is that the codeSelect() methods sometimes retrieves some RecoveredVariableBinding , and doesn't know how to build a proper Java element from those.

**Comment by mickaelistria** [comment]
Just noticed that I posted a previous comment at the wrong place https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/issues/61#issuecomment-1991830340 , repeating it here

* ResolvedVariableBinding (when type is not resolved) failing at returning a proper IJavaElement in codeSelect (either this can be fixed in JDT Core, or we need some workaround that doesn't rely on the binding resolver since the goal is to use Javac one as well). I experimentally created https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/129 .
* Field Declaration of form @Annot int x, y; are not properly populating the model: the annotation is only added to the last variable, not all of them. Submitted https://github.com/eclipse-jdtls/eclipse-jdt-core-incubator/pull/130 to hopefully fix it.
* https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2153 is also an annoyance for the case of testBug336322c

**Comment by mickaelistria** [comment]
Remaining tests seem failing because of upstream issue https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2240

**Comment by mickaelistria** [comment]
All tests passing here now.
